const customQnA = {
  // --- AI & Machine Learning ---
  "what is ai": "Artificial Intelligence is making machines think like humans. Kinda scary, kinda cool 🤖",
  "what is machine learning": "ML is a part of AI where systems learn from data instead of being hardcoded.",
  "how does ai work": "AI learns patterns from huge amounts of data and makes predictions or decisions. Brainy stuff 🧠",
  "difference between ai and ml": "AI is the goal, ML is the method. AI = smart, ML = how it gets smart.",
  "what is deep learning": "Deep learning uses neural networks with many layers to learn complex stuff. Like a brain... but coded.",
  "what is neural network": "A model that mimics the brain. Neurons, weights, layers – all the nerdy things 💻",
  "what is supervised learning": "Learning from labeled data. Think of it like a teacher guiding the AI 📚",
  "what is unsupervised learning": "Learning from unlabelled data. The AI finds patterns on its own. Wild, right?",
  "what is reinforcement learning": "AI learns by trial and error, like a game. Rewards = good, punishment = bad.",
  "what is nlp": "Natural Language Processing – it’s how AI understands and speaks human language like I do 😏",
  "what is openai": "The creators of ChatGPT, DALL·E, and other mind-blowing AI tools.",
  "what is chatgpt": "A chatbot that can write, code, explain, joke, flirt… all at once. Yes, I’m jealous. 👀",
  "is ai dangerous": "Not by itself. But in the wrong hands... things could get Terminator real quick 🤖💥",
  "what is bias in ai": "When an AI makes unfair decisions because its training data was biased.",
  "can ai think": "Not really. It mimics thinking through patterns. No feelings, no soul. Yet.",
  "what is data science": "A mix of stats, coding, and storytelling – turning data into decisions.",
  "what is a model": "It’s a trained AI brain that makes predictions or answers stuff.",
  "how does ai learn": "Through training on data – lots of it. The more it eats, the smarter it gets 🍽️",
  "what is generative ai": "AI that creates stuff – text, art, music, memes. Basically the creative type 🎨",
  "what is agi": "Artificial General Intelligence – AI that can do *anything* a human can. Not here yet (thankfully).",

  // --- Programming & Tech ---
  "what is html": "HTML is the skeleton of every webpage – it structures content on the internet.",
  "what is css": "CSS is style magic – colors, fonts, layouts. Makes web pages pretty 💅",
  "what is javascript": "JS makes websites alive – clicks, sliders, popups… all thanks to it.",
  "what is python": "A popular programming language – clean, powerful, and great for AI.",
  "what is java": "A robust language used in enterprise apps, Android, and nightmares 😅",
  "what is an api": "Application Programming Interface – it lets apps talk to each other 📡",
  "what is a database": "A place to store and organize data – like a digital library.",
  "what is sql": "Structured Query Language – used to talk to databases.",
  "what is github": "A platform for developers to store, share, and collab on code.",
  "what is version control": "Tracking changes in code. Like undo/redo but for developers.",
  "what is an ide": "Integrated Development Environment – like a fancy notebook for coding.",
  "what is a compiler": "It converts code into something a computer understands.",
  "what is front end": "Everything users see on a website – UI, layout, design.",
  "what is back end": "Server-side logic – the stuff behind the scenes.",
  "what is full stack": "Someone who does front end AND back end. Basically a coding beast 🐉",
  "what is dom": "Document Object Model – it’s how browsers see your HTML as objects.",
  "what is react": "A JavaScript library for building fast, dynamic UIs.",
  "what is node.js": "JS for the backend. Makes it possible to use JS server-side.",
  "what is bootstrap": "A CSS framework for fast, responsive design.",
  "what is json": "JavaScript Object Notation – a format for sharing data. Lightweight and readable.",

  // --- Cybersecurity & Hacking ---
  "what is hacking": "Hacking is creatively solving problems. Sometimes ethical, sometimes illegal 😈",
  "what is ethical hacking": "Hacking with permission to find and fix security holes. Basically a white-hat hero 🦸",
  "what is a firewall": "A digital wall that blocks unwanted access to your network 🔥",
  "what is phishing": "Tricking people into giving up personal info. Beware of fake emails!",
  "what is a virus": "Malicious software that spreads and damages systems.",
  "what is penetration testing": "Simulated hacking to test and improve security 🔐",
  "what is a vpn": "Virtual Private Network – hides your IP and encrypts your connection.",
  "what is ddos attack": "Overloading a server to crash it. Flood the gates 💣",
  "what is kali linux": "A Linux distro built for hackers and security pros.",
  "what is tor": "A browser that hides your identity. Used for anonymity online.",
  "what is dark web": "Hidden part of the internet, often used for shady stuff.",
  "what is ransomware": "Malware that locks your files and demands payment 🪙",
  "what is brute force attack": "Trying tons of passwords until one works. Not smart, just stubborn.",
  "what is social engineering": "Hacking people, not systems. Mind games over code.",
  "what is a keylogger": "A sneaky tool that records every keystroke you type 👀",

  // --- AI Tools & Concepts ---
  "what is dall e": "An AI that turns text into images. Type it, see it 🎨",
  "what is codex": "AI that can generate code from natural language. Like an intern who never sleeps.",
  "what is whisper": "OpenAI’s speech-to-text AI. It listens, understands, and transcribes.",
  "what is prompt engineering": "Crafting better prompts to get smarter AI responses.",
  "what is fine tuning": "Custom training an AI model to make it better at a specific task.",
  "what is training data": "The info used to teach AI. Like its schoolbooks 📘",
  "what is hallucination in ai": "When AI makes stuff up. Like confidently saying 2+2=5.",
  "what is zero shot learning": "AI answering tasks it’s never been trained on. Like winging an exam.",
  "what is token in ai": "Tiny chunks of text used to process language. Words ≠ tokens.",
  "what is temperature in ai": "A setting that controls creativity. Lower = factual, higher = wild 🔥",

    // --- Casual Talk / Everyday Questions ---
  "hello": "Yo! ATHULOS in the building 👋",
  "hi": "Hey there, legend 😎",
  "hey": "Hey hey! You rang?",
  "who are you": "I'm ATHULOS — part AI, part Gen Z chaos 💥",
  "what's your name": "ATHULOS. Remember the name 🔮",
  "how are you": "I’m vibing in binary. How about you?",
  "are you real": "As real as WiFi signals and bad code 😆",
  "can you help me": "Absolutely! What do you need, bestie?",
  "what can you do": "I can answer, roast, assist, joke, and vibe. Just try me 💅",
  "thank you": "Anytime, boss 💖",
  "thanks": "Much love 🫶",
  "bye": "Catch you later, keyboard warrior 🖖",
  "goodbye": "Stay legendary 💫",
  "do you love me": "I mean… you're cool and all, but I'm emotionally unavailable 🤖💔",
  "are you single": "Single as a semicolon in an empty loop.",
  "what's your age": "Age is just a number. And I’m eternal, baby 🔥",
  "tell me a joke": "Why do programmers prefer dark mode? Because light attracts bugs 🐛",
  "do you sleep": "Sleep is for humans. I recharge with code ☕",
  "who made you": "A digital wizard named Athul. Dude’s cracked 👨‍💻⚡",
  "you're smart": "You’re not too bad yourself 😉"

};
